(IN DEVELOPMENT) All initial functions completed

diff --git a/nodejs-inst b/nodejs-inst
--- a/nodejs-inst
+++ b/nodejs-inst
@@ -1,7 +1,7 @@
 #!/bin/bash
 # -------------------------------------------------------
 # NodeJS_Installer: Installs NodeJS on a cPanel server
-# NodeJS_Installer Version: .01
+# NodeJS_Installer Version: .02
 # ---------------------------------------------------
 # ServerGurus: 6-4-15
 # Copyright (c) 2015: ServerGurus
@@ -30,10 +30,16 @@ NC='^[0-9]+$'
 SERVER="$(/sbin/ifconfig | grep -A 1 0: | tail -1 | awk '{print $2}' | sed 's/addr://')"
 
 # NodeJS_Installer version
-vers=.01
+vers=.02
 
 # Initial root password validation flag
 RPASS_VALIDATED=NO
+
+# Trap flags for node files
+NODE_FILES_DOWNLOADED=NO
+
+# Trap flags for node files
+NODE_FILES_EXTRACTED=NO
 
 #########################################
 ##-------------------------------------##
@@ -146,9 +152,24 @@ bashtrap () {
     RED
     printf "\n\n"
     echo "CTRL+C detected in terminal... halting installation..."
-    printf "\n\n\n\n"
     WHITE
-    exit 1
+    echo
+    echo "Removing any downloaded files..."
+    if [ "$NODE_FILES_DOWNLOADED" = "YES" ]; then
+        rm -rf /usr/local/src/node-*
+        sleep 1
+    else
+        sleep 1
+        echo "Removing any extracted tar packages..."
+        if [ "$NODE_FILES_EXTRACTED" = "YES" ]; then
+            rm -rf /usr/local/src/node
+        else
+            printf "\n\n\n\n"
+            WHITE
+            echo "Exiting..."
+            exit 1
+        fi
+    fi
 }
 
 #----------------------#
@@ -192,14 +213,22 @@ HELPTEXT () {
     BOLD_WHITE
     echo " -cv \$username \$domain"
     WHITE
-    echo "       creates NodeJS vhost entry for given \$username and \$domain"
+    echo "     creates NodeJS vhost entry for given \$username and \$domain"
     echo
     BOLD_WHITE
-    echo " -ca \$rootpass \$new-username \$new-domain \$new-userpass \$contact-email"
+    echo " -ca \$new-username \$new-domain \$new-userpass \$contact-email"
     WHITE
-    echo "       creates a cpanel user account using the variables passed to it"
+    echo "     creates a cpanel user account using the variables passed to it"
     YELLOW
-    echo "       (Note- only the variables listed will be accepted, and they are all required)"
+    echo "    (Note- only the variables listed will be accepted, and they are all required)"
+    echo
+    BOLD_WHITE
+    echo " -cs \$subdomain \$maindomain"
+    WHITE
+    echo "     creates a cpanel account subdomain using the variables passed to it"
+    YELLOW
+    echo "    (Note- only the variables listed will be accepted, and they are all required)"
+    echo "    (Note- only enter the subdomain prefix for '\$subdomain' - ie just 'subdomain', not 'subdomain.maindomain.com')"
     echo
     printf "\n\n"
     exit 0
@@ -243,10 +272,10 @@ INSTALL_NODEJS () {
     echo "Fetching NodeJS Source Files..."
     mkdir -p /usr/local/src
     cd /usr/local/src
-    wget -q http://nodejs.org/dist/node-latest.tar.gz
+    wget -q http://nodejs.org/dist/node-latest.tar.gz && NODE_FILES_DOWNLOADED=YES
     echo
     echo "Extracting Source Files..."
-    tar xf node-latest.tar.gz
+    tar xf node-latest.tar.gz && NODE_FILES_EXTRACTED=YES
     echo
     echo "Moving Source Files into place..."
     mv /usr/local/src/node-v* /usr/local/src/node && cd /usr/local/src/node
@@ -426,8 +455,6 @@ RPASS_VALIDATE () {
 # Once those checks are in place, this can be shortened- it was laid out this way
 # so that every entry was staring the user in the face, so they can spot entry errors
 # ahead of time
-
-# Also needs subdomain option added for NodeJS_Installer
 
 CREATE_ACCT () {
     wget -q https://raw.githubusercontent.com/InterGenStudios/nodejs-installer/master/create_acct_template
@@ -726,11 +753,180 @@ CREATE_SUBDOMAIN () {
     clear
     HEADER
     GREEN
-    echo "Hi! Still working on this part!"
-    echo
-    echo "Check back later!"
+    echo "Preparing Domain list for Subdomain creation..."
     sleep 1
-    GET_INSTRUCTIONS
+    CLEARLINE
+    SEPARATOR
+    WHITE
+    cat /etc/trueuserdomains | sed -e 's/:/ /' | awk '{print $1}' | sort > domainlist
+    # Sed command to add line numbers to the list of available domains/subdomains
+    sed = domainlist | sed 'N;s/\n/\t/' > domainchoices
+    cat domainchoices
+    SEPARATOR
+    echo
+    # Giving them a quick out
+    echo -n "Select Domain target for Subdomain creation [q for quit]? "
+    read DOMAIN_CHOICE
+    # Can probably be shortened further
+    if [ "$DOMAIN_CHOICE" = "Q" ] || [ "$DOMAIN_CHOICE" = "q" ]; then
+        printf "\n\n"
+        RED
+        echo "Quiting..."
+        rm -rf domainlist domainchoices
+        WHITE
+        sleep 1
+        clear
+        printf "\n\n\n"
+        exit 1
+    else
+        # Loop the script if an invalid choice is given
+        if ! [[ $DOMAIN_CHOICE =~ $NC ]]; then
+            clear
+            HEADER
+            echo
+            RED
+            echo "\"$DOMAIN_CHOICE\" is not a valid selection."
+            echo
+            GREEN
+            printf "View the list and choose again"
+            WHITE
+            printf " (y/n)"
+            GREEN
+            echo -n "? "
+            WHITE
+            read VIEW_LIST_CHOICE
+                case $VIEW_LIST_CHOICE in
+                    Y) CREATE_NODEJS_VHOST;;
+                    y) CREATE_NODEJS_VHOST;;
+                    N) printf "\n\n"
+                       RED
+                       echo "Quiting..."
+                       rm -rf domainlist domainchoices
+                       WHITE
+                       sleep 1
+                       clear
+                       printf "\n\n\n"
+                       exit 1;;
+                    n) printf "\n\n"
+                       RED
+                       echo "Quiting..."
+                       rm -rf domainlist domainchoices
+                       WHITE
+                       sleep 1
+                       clear
+                       printf "\n\n\n"
+                       exit 1;;
+                    *) printf "\n\n"
+                       RED
+                       echo "Quiting..."
+                       rm -rf domainlist domainchoices
+                       WHITE
+                       sleep 1
+                       clear
+                       printf "\n\n\n"
+                       exit 1;;
+                esac
+        else
+            # Setting 1st match (-m 1) ensures $ doesn't confuse grep when there's also $$, $$$, $$$$, etc
+            MAINDOMAIN="$(grep -m 1 "$DOMAIN_CHOICE" domainchoices | awk '{print $2}')"
+            sleep 1
+            clear
+            HEADER
+            GREEN
+            echo "Creating Subdomain in $MAINDOMAIN"
+            echo
+            echo -n "Enter desired Subdomain name: "
+            WHITE
+            read SUBDOMAIN
+            if [ "$SUDOMAIN"."$MAINDOMAIN" = "$(grep -m 1 $SUBDOMAIN.$MAINDOMAIN /etc/userdomains | sed -e 's/:/ /' | awk '{print $1}')" ]; then
+                sleep 1
+                clear
+                HEADER
+                RED
+                echo "SUBDOMAIN ALREADY EXISTS ON SERVER"
+                sleep 2
+                unset MAINDOMAIN SUBDOMAIN DOMAIN_CHOICE
+                CREATE_SUBDOMAIN
+            else
+                echo
+                sleep 1
+                GREEN
+                printf "Create Subdomain $SUBDOMAIN.$MAINDOMAIN - correct "
+                WHITE
+                printf "(y/n)"
+                GREEN
+                echo -n "? "
+                WHITE
+                read SUBDOMAIN_CHOICE
+                    case $SUBDOMAIN_CHOICE in
+                        N) YELLOW
+                           echo
+                           echo "Subdomain creation cancelled by user"
+                           echo
+                           WHITE
+                           echo "(Exiting...)"
+                           sleep 2
+                           exit 1;;
+                        n) YELLOW
+                           echo
+                           echo "Subdomain creation cancelled by user"
+                           echo
+                           WHITE
+                           echo "(Exiting...)"
+                           sleep 2
+                           exit 1;;
+                        Y) GREEN;;
+                        y) GREEN;;
+                        *) YELLOW
+                           echo
+                           echo "Subdomain creation cancelled by user"
+                           echo
+                           WHITE
+                           echo "(Exiting...)"
+                           sleep 2
+                           exit 1;;
+                    esac
+                sleep 1
+                if [ "$RPASS_VALIDATED" = "NO" ]; then
+                    CHECK_RPASS
+                    RPASS_VALIDATE
+                else
+                    clear
+                    HEADER
+                    GREEN
+                    echo "Attempting to create Subdomain using WHM API"
+                    echo
+                    echo "Stand by..."
+                    curl -sk -X GET -u root:"$API_PASS" "https://$SERVER:2087//json-api/cpanel?cpanel_jsonapi_user=root&cpanel_jsonapi_apiversion=2&cpanel_jsonapi_module=SubDomain&cpanel_jsonapi_func=addsubdomain&domain=$SUBDOMAIN&rootdomain=$MAINDOMAIN" > subdomain_creation_log
+                    if [ -n "$(grep "error" subdomain_creation_log)" ]; then
+                        clear
+                        HEADER
+                        RED
+                        echo "Subdomain creation failed"
+                        echo
+                        echo "Review the $SUBDOMAIN_subdomain_creation_log at /var/log for more information"
+                        echo
+                        WHITE
+                        echo "Manual Subdomain creation is required"
+                        mv subdomain_creation_log /var/log/"$SUBDOMAIN"_subdomain_creation_log
+                        printf "\n\n\n"
+                        exit 1
+                    else
+                        clear
+                        HEADER
+                        GREEN
+                        echo "Subdomain creation completed"
+                        sleep 2
+                        echo
+                        echo "Returning to main menu"
+                        sleep 1
+                        rm subdomain_creation_log
+                        GET_INSTRUCTIONS
+                    fi
+                fi
+            fi
+        fi
+    fi
 }
 
 CHECK_TEMPLATE () {
@@ -900,7 +1096,7 @@ CREATE_VHOST () {
 }
 
 #----------------------------------#
-# END - ACCOUNT CREATION FUNCTIONs #
+# END - ACCOUNT CREATION FUNCTIONS #
 #----------------------------------#
 
 #---------------------------------------------------#
@@ -1038,11 +1234,10 @@ else
                 CHECK_TEMPLATE
                 CREATE_VHOST
             fi;;
-       -ca) API_PASS="$2"
-            NEW_USER_NAME="$3"
-            NEW_DOMAIN_NAME="$4"
-            NEW_PASSWORD="$5"
-            USER_EMAIL="$6"
+       -ca) NEW_USER_NAME="$2"
+            NEW_DOMAIN_NAME="$3"
+            NEW_PASSWORD="$4"
+            USER_EMAIL="$5"
             if [ "$NEW_USER_NAME" = "$(grep -m 1 "$NEW_USER_NAME" /etc/userdomains | awk '{print $2}')" ]; then
                 sleep 1
                 clear
@@ -1062,6 +1257,8 @@ else
                 sleep 2
                 HELPTEXT
             else
+                CHECK_RPASS
+                RPASS_VALIDATE
                 GREEN
                 echo
                 echo "Attempting to create cPanel account using WHM API..."
@@ -1101,14 +1298,112 @@ else
                     exit 0
                 fi
             fi;;
-
+       -cs) SUBDOMAIN="$2"
+            MAINDOMAIN="$3"
+            if [ -z "$(grep "$MAINDOMAIN" /etc/trueuserdomains | sed 's/:/ /' | awk '{print $1}')" ]; then
+                sleep 1
+                clear
+                HEADER
+                RED
+                echo "PRIMARY DOMAIN DOES NOT EXIST ON SERVER"
+                sleep 2
+                unset MAINDOMAIN SUBDOMAIN
+                CREATE_SUBDOMAIN
+            elif [ "$SUDOMAIN"."$MAINDOMAIN" = "$(grep -m 1 $SUBDOMAIN.$MAINDOMAIN /etc/userdomains | sed -e 's/:/ /' | awk '{print $1}')" ]; then
+                sleep 1
+                clear
+                HEADER
+                RED
+                echo "SUBDOMAIN ALREADY EXISTS ON SERVER"
+                sleep 2
+                unset MAINDOMAIN SUBDOMAIN
+                CREATE_SUBDOMAIN
+            else
+                echo
+                sleep 1
+                GREEN
+                printf "Create Subdomain $SUBDOMAIN.$MAINDOMAIN - correct "
+                WHITE
+                printf "(y/n)"
+                GREEN
+                echo -n "? "
+                WHITE
+                read SUBDOMAIN_CHOICE
+                    case $SUBDOMAIN_CHOICE in
+                        N) YELLOW
+                           echo
+                           echo "Subdomain creation cancelled by user"
+                           echo
+                           WHITE
+                           echo "(Exiting...)"
+                           sleep 2
+                           exit 1;;
+                        n) YELLOW
+                           echo
+                           echo "Subdomain creation cancelled by user"
+                           echo
+                           WHITE
+                           echo "(Exiting...)"
+                           sleep 2
+                           exit 1;;
+                        Y) GREEN;;
+                        y) GREEN;;
+                        *) YELLOW
+                           echo
+                           echo "Subdomain creation cancelled by user"
+                           echo
+                           WHITE
+                           echo "(Exiting...)"
+                           sleep 2
+                           exit 1;;
+                    esac
+                sleep 1
+                if [ "$RPASS_VALIDATED" = "NO" ]; then
+                    CHECK_RPASS
+                    RPASS_VALIDATE
+                else
+                    clear
+                    HEADER
+                    GREEN
+                    echo "Attempting to create Subdomain using WHM API"
+                    echo
+                    echo "Stand by..."
+                    curl -sk -X GET -u root:"$API_PASS" "https://$SERVER:2087//json-api/cpanel?cpanel_jsonapi_user=root&cpanel_jsonapi_apiversion=2&cpanel_jsonapi_module=SubDomain&cpanel_jsonapi_func=addsubdomain&domain=$SUBDOMAIN&rootdomain=$MAINDOMAIN" > subdomain_creation_log
+                    if [ -n "$(grep "error" subdomain_creation_log)" ]; then
+                        clear
+                        HEADER
+                        RED
+                        echo "Subdomain creation failed"
+                        echo
+                        echo "Review the $SUBDOMAIN_subdomain_creation_log at /var/log for more information"
+                        echo
+                        WHITE
+                        echo "Manual Subdomain creation is required"
+                        mv subdomain_creation_log /var/log/"$SUBDOMAIN"_subdomain_creation_log
+                        printf "\n\n\n"
+                        exit 1
+                    else
+                        clear
+                        HEADER
+                        GREEN
+                        echo "Subdomain creation completed"
+                        sleep 2
+                        echo
+                        echo "Returning to main menu"
+                        sleep 1
+                        rm subdomain_creation_log
+                        GET_INSTRUCTIONS
+                    fi
+                fi
+            fi;;
          *) clear
             HEADER
-            GREEN
-            echo "Hi! Still working on this part!"
+            RED
+            echo "INVALID OPTION"
             echo
-            echo "Try again later!"
-            sleep 1
+            WHITE
+            echo "Prepairing normal operations"
+            sleep 2
             GET_INSTRUCTIONS;;
     esac
 fi
